"""empty message

Revision ID: cd9a353b1a03
Revises: ef45ed404ad5
Create Date: 2025-12-31 08:21:34.318394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd9a353b1a03'
down_revision = 'ef45ed404ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.alter_column('favorite_color',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('favorite_color',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
